app/models/__init__.py
from .comment import Comment

app/models/comment.py
from app import db


class Comment(db.Model):
    """
    Comment
    """

    __tablename__ = "comments"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    content = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=db.func.now())

app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class CommentForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Submit")


class EditCommentForm(CommentForm):
    submit = SubmitField("Update")

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap

from config import app_config

db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile("config.py")

    db.init_app(app)

    Migrate(app, db)
    Bootstrap(app)

    from app import models

    from .home import home as home_blueprint

    app.register_blueprint(home_blueprint)

    return app

app/home/__init__.py
from flask import Blueprint

home = Blueprint("home", __name__)

from . import views

app/home/views.py
from flask import render_template, redirect, url_for
from sqlalchemy import desc
from ..models import Comment
from .. import db

from . import home
from .forms import CommentForm, EditCommentForm


@home.route("/", methods=["GET", "POST"])
def index():
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(name=form.name.data, content=form.content.data)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for("home.index"))
    comments = Comment.query.order_by(desc(Comment.created_at)).all()
    return render_template(
        "home/index.html", title="Home", form=form, comments=comments
    )


@home.route("/edit/<int:id>", methods=["GET", "POST"])
def edit(id):
    comments = Comment.query.all()
    comment = Comment.query.get(id)
    form = EditCommentForm(name=comment.name, content=comment.content)
    if form.validate_on_submit():
        comment.name = form.name.data
        comment.content = form.content.data
        db.session.commit()

        return redirect(url_for("home.index"))

    return render_template(
        "home/index.html", title="Edit", form=form, comments=comments
    )


@home.route("/delete/<int:id>")
def delete(id):
    comment = Comment.query.get(id)
    db.session.delete(comment)
    db.session.commit()

    return redirect(url_for("home.index"))

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>{{ title }} | Flask Guestbook</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    <div class="mb-4"></div>
    <div class="container">
    {% block body %}{% endblock %}
    </div>
  </body>
</html>

app/templates/home/index.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block body %}
<div class="row">
  <div class="col-8">
    {% for comment in comments %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">{{ comment.name }} @ <span>{{ comment.created_at }}</span></h5>
        <p class="card-text">{{ comment.content }}</p>
        <div>
          <a href="{{ url_for("home.edit", id=comment.id) }}" class="btn btn-secondary">Edit</a>
          <a href="{{ url_for("home.delete", id=comment.id) }}" class="ml-2 btn btn-danger">Delete</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="col-4">
    {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}
  </div>
</div>
{% endblock %}